import { db } from './client';
import { activities, categories, targets, trips, users } from './schema';

export async function seedDatabaseIfEmpty() {
  const existingUsers = await db.select().from(users);

  if (existingUsers.length > 0) return;

  await db.insert(users).values([
    {
      id: 1,
      name: 'Ava Student',
      email: 'ava@example.com',
      password: 'password123',
      createdAt: '2026-04-21',
    },
  ]);

  await db.insert(trips).values([
    {
      id: 1,
      userId: 1,
      name: 'Barcelona City Break',
      destination: 'Barcelona, Spain',
      startDate: '2026-05-10',
      endDate: '2026-05-15',
      notes: 'Spring holiday with lots of walking and food spots.',
    },
    {
      id: 2,
      userId: 1,
      name: 'Alps Adventure',
      destination: 'Chamonix, France',
      startDate: '2026-06-02',
      endDate: '2026-06-08',
      notes: 'Outdoor-focused trip with hikes and scenic activities.',
    },
  ]);

  await db.insert(categories).values([
    {
      id: 1,
      userId: 1,
      name: 'Sightseeing',
      color: '#3B82F6',
      icon: 'camera',
    },
    {
      id: 2,
      userId: 1,
      name: 'Food',
      color: '#F97316',
      icon: 'restaurant',
    },
    {
      id: 3,
      userId: 1,
      name: 'Outdoor',
      color: '#22C55E',
      icon: 'leaf',
    },
    {
      id: 4,
      userId: 1,
      name: 'Travel',
      color: '#8B5CF6',
      icon: 'airplane',
    },
    {
      id: 5,
      userId: 1,
      name: 'Relaxation',
      color: '#EC4899',
      icon: 'bed',
    },
  ]);

  await db.insert(activities).values([
    {
      id: 1,
      tripId: 1,
      categoryId: 1,
      title: 'Sagrada Familia visit',
      date: '2026-05-10',
      metricValue: 120,
      metricUnit: 'minutes',
      notes: 'Booked morning slot.',
      isCompleted: 1,
    },
    {
      id: 2,
      tripId: 1,
      categoryId: 2,
      title: 'Tapas dinner',
      date: '2026-05-10',
      metricValue: 90,
      metricUnit: 'minutes',
      notes: 'Gothic Quarter restaurant.',
      isCompleted: 1,
    },
    {
      id: 3,
      tripId: 1,
      categoryId: 1,
      title: 'Park Güell walk',
      date: '2026-05-11',
      metricValue: 100,
      metricUnit: 'minutes',
      notes: 'Afternoon activity.',
      isCompleted: 1,
    },
    {
      id: 4,
      tripId: 1,
      categoryId: 4,
      title: 'Metro travel pass usage',
      date: '2026-05-11',
      metricValue: 4,
      metricUnit: 'count',
      notes: 'Four journeys in one day.',
      isCompleted: 1,
    },
    {
      id: 5,
      tripId: 1,
      categoryId: 5,
      title: 'Beach downtime',
      date: '2026-05-12',
      metricValue: 150,
      metricUnit: 'minutes',
      notes: 'Barceloneta beach.',
      isCompleted: 1,
    },
    {
      id: 6,
      tripId: 1,
      categoryId: 2,
      title: 'Market food tasting',
      date: '2026-05-12',
      metricValue: 60,
      metricUnit: 'minutes',
      notes: 'La Boqueria visit.',
      isCompleted: 1,
    },
    {
      id: 7,
      tripId: 2,
      categoryId: 3,
      title: 'Mountain hike',
      date: '2026-06-03',
      metricValue: 240,
      metricUnit: 'minutes',
      notes: 'Long trail day.',
      isCompleted: 1,
    },
    {
      id: 8,
      tripId: 2,
      categoryId: 3,
      title: 'Lake walk',
      date: '2026-06-04',
      metricValue: 95,
      metricUnit: 'minutes',
      notes: 'Easy recovery day.',
      isCompleted: 1,
    },
    {
      id: 9,
      tripId: 2,
      categoryId: 4,
      title: 'Cable car rides',
      date: '2026-06-04',
      metricValue: 2,
      metricUnit: 'count',
      notes: 'Return trip.',
      isCompleted: 1,
    },
    {
      id: 10,
      tripId: 2,
      categoryId: 2,
      title: 'Dinner in town',
      date: '2026-06-05',
      metricValue: 75,
      metricUnit: 'minutes',
      notes: 'Booked local restaurant.',
      isCompleted: 1,
    },
    {
      id: 11,
      tripId: 2,
      categoryId: 5,
      title: 'Spa session',
      date: '2026-06-06',
      metricValue: 120,
      metricUnit: 'minutes',
      notes: 'Evening relaxation.',
      isCompleted: 1,
    },
    {
      id: 12,
      tripId: 2,
      categoryId: 1,
      title: 'Town centre photo walk',
      date: '2026-06-06',
      metricValue: 80,
      metricUnit: 'minutes',
      notes: 'Scenic walk through the town.',
      isCompleted: 1,
    },
  ]);

  await db.insert(targets).values([
    {
      id: 1,
      userId: 1,
      categoryId: null,
      period: 'weekly',
      metricType: 'minutes',
      goal: 300,
      title: 'Weekly total activity minutes',
    },
    {
      id: 2,
      userId: 1,
      categoryId: 3,
      period: 'weekly',
      metricType: 'minutes',
      goal: 180,
      title: 'Weekly outdoor minutes',
    },
    {
      id: 3,
      userId: 1,
      categoryId: 1,
      period: 'monthly',
      metricType: 'count',
      goal: 4,
      title: 'Monthly sightseeing activities',
    },
  ]);
}